### PR TITLE
feat: #374 format function editor

### PR DESCRIPTION
**Pull request by caleblamro**
This PR is related to issue #374. I was finding myself wanting to be able to easily format functions directly in the function editor. I decided to implement this myself, as well as format the function on load (not sure if we want to do this, or if we should do it in a different way).

### CODE REVIEW

**Comment by caleblamro** [comment]
Not sure why the checks are failing... I only changed one file and didn't add any packages or anything like that. Any ideas as to why this is happening?

**Comment by caleblamro** [comment]
Probably should get rid of the `useEffect`, but I think this should be implemented somehow. If someone could walk me through how to implement this functionality I'd be very grateful. I think having the functions automatically formatted would be very nice.

**Comment by macjuul** [comment]
Thank you so much for the PR! This is indeed a great improvement. I'm not sure why the actions are failing however I can see it's unrelated to your changes so let's ignore it for now.

As for the `useEffect`, the proper way to implement this would be to update the [editFunction](https://github.com/surrealdb/surrealist/blob/1fca82f68699fd192ffd2e786a9a3ce920c6c664/src/screens/database/views/functions/FunctionsView/index.tsx#L70) function in the parent FunctionsView component. You could simply object spread the function and overwrite the block with it's formatted version. Hope that helps!

**Comment by caleblamro** [comment]
I'll go ahead and make those changes. Thank you for reviewing! I'll see if I can debug the checks passing as well.

**Comment by macjuul** [comment]
Awesome, I actually ended up fixing the build errors on main, so feel free to rebase your branch

**Comment by caleblamro** [comment]
Great. I'll go ahead and do that. Thank you!

**Comment by caleblamro** [comment]
I just realized I do not have the correct formatting. I'll fix that now.

**Comment by macjuul** [comment]
LGTM! Thanks for the PR 😃

**Pull request merged**
