### PR TITLE
feature: Have config.json pretty printed

### PR DESCRIPTION
**Pull request by winksaville**
Using jsonxf to pretty print config.json when saving.

### CODE REVIEW

**Comment by winksaville** [comment]
I believe having `config.json` pretty printed makes it more useful for humans.

I've chosen jsonxf simply because when searching crates.io it was most relevant and had almost 100,000 downloads. Another obvious choice would be to use [serde_json::to_string_pretty](https://docs.rs/serde_json/latest/serde_json/fn.to_string_pretty.html) but since serde wasn't being used currently I thought maybe there was a reason not to so looked for another alternative.

**Review by macjuul — APPROVED** [review]

**Comment by winksaville** [comment]
Rebased and altered this PR to build on main. In that surrealdb/src-tauri/Cargo.toml now has serde & serde_json as dependencies I switched to using serde_json::to_string_pretty, this simplifies the change and it's now only a two line change to surrealdb/src-tauri/src/config.rs.

**Comment by macjuul** [comment]
LGTM! Thanks!

**Comment by macjuul** [comment]
I have changed the implementation back to using jsonxf as serde caused the entire config to be saved as a single JSON string, corrupting it in the process 😅

**Comment by winksaville** [comment]
OMG, I'm so sorry :(

**Pull request merged**
