### PR TITLE
feat: add additional keymap

### PR DESCRIPTION
**Pull request by Odonno**
Improve experience by adding vscode keymap.
At least for me, it make `CTRL+K+C` and `CTRL+K+U` works.

* Add `vscode-keymap` plugin to add additional keymaps https://github.com/replit/codemirror-vscode-keymap
* Disable `mod+K` hotkey confitionally (disabled when in-editor) to be able to use `CTRL+K+C` and `CTRL+K+U`. Search window still works outside the query editor
* Added `hasEditorFocus` and `setHasEditorFocus` in the `InterfaceStore`

Note: there is a warning to set `defaultKeymap: false`. I did not make this change and still to work as-is. I am note sure if anything is broken.

### CODE REVIEW

**Comment by macjuul** [comment]
I'm absolutely up for adding additional shortcuts and adopting the vscode keymap, however I think it's important for cmd+K to remain working within editors (and everywhere else throughout the app), even if this means we have to drop or preferably remap certain shortcuts

**Comment by Odonno** [comment]
I can understand the point. Better stick with consistency. But it just feels frustrating not to be able to use the common comment/uncomment key bindings, even more frustrating when it opens the command palette.

One idea could be to offer a remapping of key bindings. Kind of what video games offers. But that seems too much effort and code for such a feature.

Another idea that can be simple to do could be to disable command palette (via feature flag) so that we can enable the comment key bindings. It would be trading a feature for another. Not liking it much though.

**Comment by macjuul** [comment]
I'm satisfied if we keep commenting on `cmd + /` so we can leave `cmd + K` accessible from editors

**Comment by macjuul** [comment]
Closing this PR as Surrealist now provides keybind customisation

**Pull request closed without merging**
